linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - unused
    # - cyclop

run:
  issues-exit-code: 1
  timeout: 2m
  tests: false

linters-settings:
  cyclop:
    skip-tests: true
    max-complexity: 15
    package-average: 4
