global:
  evaluation_interval: 30s
  scrape_interval: 5s
  external_labels:
    source: 'prometheus'
    environment: 'development'
    service: 'example-service'
scrape_configs:
- job_name: 'example-service'
  static_configs:
    - targets: ['localhost:8091'] 