# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
    
    - name: verify dependencies
      run: go mod verify

    - name: install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: run staticcheck
      run: staticcheck ./...

    - name: install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: run golangci-lint
      run: golangci-lint run --timeout 5m

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
